part1 and part2 of exe1
jenupawan/-rust-protobuf-exe1 pull request #2
Opened 2020-06-16 16:04 UTC by jenupawan

2020-06-17 20:18 UTC, shashank676 requested changes

2020-06-17 20:18 UTC, shashank676 commented on message_generoator/Cargo.toml
> +name = "message_generoator"
typo: message_generator

2020-06-17 20:18 UTC, shashank676 commented on message_generoator/proto_file/person.proto
> +}
always have a new line at the end of the file

2020-06-17 20:18 UTC, shashank676 commented on message_generoator/src/main.rs
> +        .expect("Running protoc failed.");
improve error msg

2020-06-17 20:18 UTC, shashank676 commented on proto/protos/.rustc_info.json
> +{"rustc_fingerprint":16456912848005604488,"outputs":{"16929990295604814582":["___\n",""],"1164083562126845933":["rustc 1.46.0-nightly (fd4b177aa 2020-06-08)\nbinary: rustc\ncommit-hash: fd4b177aabb97
no need to push this file in repo

2020-06-17 20:18 UTC, shashank676 commented on proto/protos/per.proto
> +}
new line at eof missing

2020-06-17 20:18 UTC, shashank676 commented on proto/src/main.rs
> +                .help("path for input file with data")
"path of the input file" is sufficient

2020-06-17 20:18 UTC, shashank676 commented on proto/src/main.rs
> +    let input_path = matches.value_of("input").unwrap_or("data/input.txt");
using unwrap_or is not a good option, if input path is not correct u need to throw error

2020-06-17 20:18 UTC, shashank676 commented on proto/src/main.rs
> +    let output_path = matches.value_of("output").unwrap_or("data/output.txt");
same as above

2020-06-17 20:18 UTC, shashank676 commented on proto/src/main.rs
> +    let mut ofile = File::create(output_path).expect("unable to create file");
use correct naming convention

2020-06-17 20:18 UTC, shashank676 commented on proto/src/main.rs
> +        }
remember this String uses heap memory whereas &str uses stack memory. stack memory is used for static memory allocation and Heap for dynamic memory allocation, both stored in the computer's RAM. Variables allocated on the stack are stored directly to the memory and access to this memory is very fast, and its allocation is dealt with when the program is compiled.
so it better to use
**let line_info: Vec<&str> = each_line.split(',').collect();**

2020-06-17 20:18 UTC, shashank676 commented on proto/src/main.rs
> +use person::Person as person_obj;
rust is not object oriented, using terminologies like person obj...doesn't make much sense

2020-06-17 20:18 UTC, shashank676 commented on proto/src/main.rs
> +use person::Person as person_obj;
i'll prefer Person as it is

2020-06-17 20:18 UTC, shashank676 commented on proto2/Cargo.toml
> +clap = "2.33.1"
newline at eof missing

2020-06-17 20:18 UTC, shashank676 commented on proto2/data/output.txt
> +last_name: "Beckman" first_name: "Diane" dob: "1963-02-28" age:0years 5month 1days
age calc looks incorrect

2020-06-17 20:18 UTC, shashank676 commented on proto2/data/output.txt
> +last_name: "Beckman" first_name: "Diane" dob: "1963-02-28" age:0years 5month 1days
0 years for different dob how is it possible

2020-06-17 20:18 UTC, shashank676 commented on proto2/src/calc_age.rs
> +}
unit test must cover all possible edge cases, otherwise, it's of no use

2020-06-17 20:18 UTC, shashank676 commented on proto2/data/output.txt
> +last_name: "Beckman" first_name: "Diane" dob: "1963-02-28" age:0years 5month 1days
this type of cases should be covered in unit testing

2020-06-17 20:18 UTC, shashank676 commented on proto2/data/output.txt
> +last_name: "Beckman" first_name: "Diane" dob: "1963-02-28" age:0years 5month 1days
how did u verify ur output? @jenupawan

2020-06-17 20:18 UTC, shashank676 commented on proto2/src/main.rs
> +    )
same comments as in prev program

2020-06-17 20:18 UTC, shashank676 commented on proto2/src/main.rs
> +let output_path = matches.value_of("output").unwrap_or("data/output.txt");
same here as prev progm

2020-06-17 20:18 UTC, shashank676 commented on proto2/src/main.rs
> +let mut ofile = File::create(output_path).expect("unable to create file");
same

2020-06-17 20:18 UTC, shashank676 commented on proto2/src/main.rs
> +
y this new line

2020-06-17 20:18 UTC, shashank676 commented on proto2/src/main.rs
> +        let person_from_file:person_obj = stream.read_message().unwrap();
did u run cargo fmt?? @jenupawan

2020-06-17 20:18 UTC, shashank676 commented on proto2/src/main.rs
> +        let person_from_file:person_obj = stream.read_message().unwrap();
ur code is not indented correctly

2020-06-17 20:18 UTC, shashank676 commented on proto2/src/main.rs
> +        let person_from_file:person_obj = stream.read_message().unwrap();
I mentioned no unwrap() always use expect()

2020-06-17 20:18 UTC, shashank676 commented on proto2/src/main.rs
> +        let person_from_file:person_obj = stream.read_message().unwrap();
put a cfg condition for checking such violations in the code....at compile time

2020-06-17 20:18 UTC, shashank676 commented on proto2/src/main.rs
> +        let  person_date = Utc.from_local_date(&date_only.unwrap()).unwrap();
no unwrap()

2020-06-17 20:18 UTC, shashank676 commented on proto2/src/main.rs
> +        let  person_date = Utc.from_local_date(&date_only.unwrap()).unwrap();
check the logic used here

2020-06-17 20:18 UTC, shashank676 commented on proto2/src/calc_age.rs
> +  let month:Vec<i32>= vec![31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
plural variable name.....use appropriate var names

2020-06-17 20:18 UTC, shashank676 commented on proto2/src/calc_age.rs
> +  let  birth_year = person_date.year()as i32;
cargo fmt not run

2020-06-17 20:18 UTC, shashank676 commented on proto2/src/calc_age.rs
> +  let current = Utc::now().date();
use system now, in this case

2020-06-18 03:40 UTC, jenupawan commented on proto/protos/per.proto
> +}
@shashank676 , I think this file is not needed anymore, as I will be generating the .rs file in my message_generator project, so can I delete it ?

2020-06-18 03:44 UTC, jenupawan commented on proto/src/main.rs
> +    let input_path = matches.value_of("input").unwrap_or("data/input.txt");
@shashank676 , what kind of error message to throw inline 34, as am getting the path from command line?

2020-06-19 05:57 UTC, shashank676 approved these changes

2020-06-19 05:59 UTC, shashank676 commented
please make logical commits

2020-06-19 06:00 UTC, shashank676 requested changes
code is fine now @pawanjenu but 20 commits is not correct. You should be writing logical commits

2020-06-19 09:24 UTC, shashank676 approved these changes

2020-06-19 09:24 UTC, merged